packages:
  - .

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
allowBuilds:
  bufferutil: true
  dtrace-provider: false
  electron-winstaller: true
  esbuild: true
  ip-set: true
  node-datachannel: true
  utf-8-validate: true
  utp-native: true
overrides:
  ip-address: 10.3.1
  fast-uri: 3.1.5
  js-yaml: 4.3.0
