onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
allowBuilds:
  bufferutil: true
  electron-winstaller: true
  esbuild: true
  ip-set: true
  node-datachannel: true
  utf-8-validate: true
  utp-native: true
