import type { OplApi } from '@/types/opl'

const unsupported = async () => {
  throw new Error('API Electron indisponivel. Abra o app via pnpm electron:dev.')
}

const fallbackApi: OplApi = {
  enqueueDownload: unsupported,
  listDownloads: async () => ({ items: [], revision: 0 }),
  getDurableDownload: async () => undefined,
  pauseDurableDownload: unsupported,
  resumeDurableDownload: unsupported,
  retryDurableDownload: unsupported,
  cancelDurableDownload: unsupported,
  retryFailedDownloads: unsupported,
  clearTerminalDownloads: unsupported,
  getFinalizationPlan: async () => undefined,
  confirmFinalization: unsupported,
  setFinalizationGameId: unsupported,
  cancelFinalization: unsupported,
  refreshArtIndex: unsupported,
  queryArtIndex: async () => ({ items: [], revision: 0 }),
  createArtSyncPlan: unsupported,
  startArtSync: unsupported,
  getArtSyncJob: async () => undefined,
  listArtSyncJobs: async () => ({ items: [], revision: 0 }),
  pauseArtSync: unsupported,
  resumeArtSync: unsupported,
  cancelArtSync: unsupported,
  retryFailedArtSync: unsupported,
  onOplPipelineEvent: () => () => undefined,
  auditOplNaming: unsupported,
  createOplNamingPlan: unsupported,
  confirmOplNaming: unsupported,
  getOplNamingOperation: async () => undefined,
  listFragmentationGames: unsupported,
  diagnoseFragmentation: unsupported,
  getCurrentFragmentationDiagnosis: async () => undefined,
  cancelFragmentationDiagnosis: unsupported,
  planFragmentationRepair: unsupported,
  confirmFragmentationRepair: unsupported,
  cancelFragmentationRepair: unsupported,
  getFragmentationRepairOperation: async () => undefined,
  getFragmentationRepairReport: async () => undefined,
  getFragmentationRepairReportByOperation: async () => undefined,
  listFragmentationRecovery: async () => [],
  resolveFragmentationRecovery: unsupported,
  listOplProfiles: async () => [],
  getOplProfile: async () => undefined,
  registerOfficialOpl: unsupported,
  planOplUpdate: unsupported,
  confirmOplUpdate: unsupported,
  planInstallation: unsupported,
  confirmInstallation: unsupported,
  cancelInstallation: unsupported,
  scanCatalog: unsupported,
  cancelCatalogScan: unsupported,
  getCatalogSnapshot: async () => undefined,
  setCatalogGameId: unsupported,
  hashCatalogFile: unsupported,
  runDiagnostics: unsupported,
  indexArt: async () => [],
  planArtSync: unsupported,
  confirmArtSync: unsupported,
  detectPcsx2: unsupported,
  planValidation: unsupported,
  startValidation: unsupported,
  confirmValidationCheckpoint: unsupported,
  stopValidation: unsupported,
  planReorganization: unsupported,
  confirmReorganization: unsupported,
  cancelReorganization: unsupported,
  generateReadinessReport: unsupported,
  getReadinessReport: async () => undefined,
  recordHardwareSmoke: unsupported,
  exportReadinessReport: unsupported,
  getNetworkShareConfig: unsupported,
  saveNetworkShareConfig: unsupported,
  acknowledgeNetworkShareWriteAccess: unsupported,
  startNetworkShare: unsupported,
  stopNetworkShare: unsupported,
  getNetworkShareStatus: async () => ({
    smb: { state: 'off', boundAddresses: [] },
    ftp: { state: 'off', boundAddresses: [] },
    connectedClients: []
  }),
  getNetworkShareSetupInstructions: unsupported,
  onNetworkShareEvent: () => () => undefined,
  listDevices: async () => [],
  getDeviceSummary: async () => ({
    device: null,
    ps2Games: 0,
    ps1Games: 0,
    apps: 0,
    recentHistory: []
  }),
  prepareDevice: unsupported,
  copyGame: unsupported,
  copyPs1Game: unsupported,
  installApp: unsupported,
  listInstalledApps: async () => [],
  removeApp: unsupported,
  listSourceFiles: async () => [],
  importFromSource: unsupported,
  listManagedSources: async () => [],
  saveManagedSource: unsupported,
  removeManagedSource: unsupported,
  searchRemoteSource: async () => [],
  getRemoteItemDetails: unsupported,
  listRemoteFiles: async () => [],
  addP2PDownload: unsupported,
  addCatalogGamesToQueue: unsupported,
  pauseDownload: unsupported,
  resumeDownload: unsupported,
  cancelDownload: unsupported,
  getDownloadQueue: async () => [],
  getDownloadProgress: unsupported,
  listEssentialsCatalog: async () => [],
  refreshEssentialsSourceLinks: unsupported,
  createSmartFillPlan: unsupported,
  listTorrentFiles: async () => [],
  selectTorrentFiles: unsupported,
  startTorrentDownload: unsupported,
  detectGameId: async () => null,
  saveGameLibraryEntry: unsupported,
  getGameLibrary: async () => ({ games: [] }),
  openFolder: unsupported,
  openExternalUrl: unsupported,
  getHistory: async () => [],
  clearHistory: async () => undefined,
  openPathDialog: async () => [],
  onLog: () => () => undefined,
  onProgress: () => () => undefined,
  onOperationEvent: () => () => undefined,
  onFragmentationRepairEvent: () => () => undefined,
  onCatalogEvent: () => () => undefined,
  onValidationEvent: () => () => undefined,
  onDownloadProgress: () => () => undefined,
  onDownloadCompleted: () => () => undefined,
  onDownloadFailed: () => () => undefined
}

export const oplApi: OplApi =
  typeof window !== 'undefined' && window.oplApi ? window.oplApi : fallbackApi
